// <auto-generated />
using System;
using CLIProfessor.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using Pgvector;

#nullable disable

namespace CLIProfessor.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "vector");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CLIProfessor.Domain.Entities.CommandRequest", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NaturalLanguageInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("CommandRequests");
                });

            modelBuilder.Entity("CLIProfessor.Domain.Entities.LearnedCorrection", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CorrectedCommand")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<Vector>("Embedding")
                        .HasColumnType("vector(768)");

                    b.Property<string>("Explanation")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("LearnedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("OriginalInput")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("LearnedCorrections");
                });

            modelBuilder.Entity("CLIProfessor.Domain.Entities.CommandRequest", b =>
                {
                    b.OwnsOne("CLIProfessor.Domain.Entities.TerminalContext", "Context", b1 =>
                        {
                            b1.Property<Guid>("CommandRequestId")
                                .HasColumnType("uuid");

                            b1.Property<string>("CurrentDirectory")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("OS")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.Property<string>("Shell")
                                .IsRequired()
                                .HasColumnType("text");

                            b1.HasKey("CommandRequestId");

                            b1.ToTable("CommandRequests");

                            b1.WithOwner()
                                .HasForeignKey("CommandRequestId");
                        });

                    b.Navigation("Context")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
